### ISSUE TITLE
Can't return false when using getAndBindTo

### ISSUE THREAD

**Issue by outadoc** [jcheron/phalcon-jquery#1]
When using getAndBindTo() or similar, it is impossible to prevent the default event from being fired, unlike when using a function like click(), which offers the $ret_false parameter.

This makes it impossible to click on an anchor without having the page scroll all the way up, or at least not in any straightforward way.

**Comment by jcheron** [comment]
Yes, it is unacceptable ...
fixed with https://github.com/jcheron/phalcon-jquery/commit/6dc8812f45b884ef42d0f08a78385c98e160fa11
preventDefault parameter is now present in all **get/post/postForm...AndBindTo** methods (default to true)

``` php
    public function getAndBindTo($element,$event,$url,$responseElement="",$preventDefault=true,$params="{}",$function=NULL,$attr="id"){
...
}
```

**Comment by jcheron** [comment]
there is also no way to stop propagation of events ...
Considering the number of function parameters, I think the next implementation should be : 

``` php
public function getAndBindTo($element,$event,$url,$responseElement="", $parameters=array())
```

Thank you for reporting
